'use client';

import { useState } from 'react';
import Link from 'next/link';
import { Eye, FileClock, Trash2 } from 'lucide-react';
import PageHeader from '@/components/admin/PageHeader';
import TableSkeleton from '@/components/admin/TableSkeleton';
import EmptyState from '@/components/admin/EmptyState';
import ConfirmDialog from '@/components/admin/ConfirmDialog';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { useDeleteStatementHistory, useStatementHistory } from '@/hooks/useInvoices';
import { useAuth } from '@/hooks/useAuth';
import { toast } from '@/hooks/useToast';
import { formatDate } from '@/lib/utils/formatters';

function dateRange(statement) {
  if (!statement.startDate || !statement.endDate) return '—';
  return `${formatDate(statement.startDate)} – ${formatDate(statement.endDate)}`;
}

function generatedByLabel(generatedBy) {
  return generatedBy?.username ?? generatedBy?.email ?? 'Unknown user';
}

export default function InvoiceStatementHistoryPage() {
  const [page, setPage] = useState(1);
  const [deleteTarget, setDeleteTarget] = useState(null);
  const { hasPermission } = useAuth();
  const canDelete = hasPermission('invoice.delete');
  const { data, isLoading, error } = useStatementHistory({ page, limit: 20 });
  const deleteHistory = useDeleteStatementHistory();
  const statements = data?.statements ?? [];

  async function handleDelete() {
    if (!deleteTarget) return;
    try {
      await deleteHistory.mutateAsync(deleteTarget._id);
      toast({ title: `${deleteTarget.statementNumber} deleted` });
      setDeleteTarget(null);
    } catch (err) {
      toast({ title: err?.message ?? 'Statement deletion failed', variant: 'destructive' });
    }
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Invoice Statement History"
        description="View and manage permanently stored statement PDFs"
        action={
          <Button asChild variant="outline" size="sm">
            <Link href="/invoices/statements">Generate Statement</Link>
          </Button>
        }
      />

      <Card>
        {isLoading ? (
          <CardContent className="p-6">
            <TableSkeleton rows={6} cols={6} />
          </CardContent>
        ) : error ? (
          <CardContent className="p-6 text-sm text-destructive">
            {error?.message ?? 'Failed to load statement history'}
          </CardContent>
        ) : statements.length === 0 ? (
          <CardContent className="p-0">
            <EmptyState
              icon={FileClock}
              title="No statement history"
              description="Downloaded statement PDFs will appear here."
              className="m-6"
            />
          </CardContent>
        ) : (
          <CardContent className="p-0">
            <div className="overflow-x-auto">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Statement Number</TableHead>
                    <TableHead className="text-center">Invoice Count</TableHead>
                    <TableHead>Date Range</TableHead>
                    <TableHead>Generated By</TableHead>
                    <TableHead>Generated At</TableHead>
                    <TableHead className="text-right">Actions</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {statements.map((statement) => (
                    <TableRow key={statement._id}>
                      <TableCell className="font-medium">{statement.statementNumber}</TableCell>
                      <TableCell className="text-center tabular-nums">
                        {statement.invoiceCount}
                      </TableCell>
                      <TableCell className="whitespace-nowrap text-muted-foreground">
                        {dateRange(statement)}
                      </TableCell>
                      <TableCell>{generatedByLabel(statement.generatedBy)}</TableCell>
                      <TableCell className="whitespace-nowrap text-muted-foreground">
                        {formatDate(statement.generatedAt, {
                          year: 'numeric',
                          month: 'short',
                          day: 'numeric',
                          hour: '2-digit',
                          minute: '2-digit',
                        })}
                      </TableCell>
                      <TableCell>
                        <div className="flex justify-end gap-1">
                          <Button asChild variant="ghost" size="icon">
                            <a
                              href={`/invoices/statements/history/${statement._id}`}
                              aria-label={`View ${statement.statementNumber}`}
                            >
                              <Eye className="h-4 w-4" />
                            </a>
                          </Button>
                          {canDelete && (
                            <Button
                              variant="ghost"
                              size="icon"
                              className="text-destructive hover:text-destructive"
                              aria-label={`Delete ${statement.statementNumber}`}
                              onClick={() => setDeleteTarget(statement)}
                            >
                              <Trash2 className="h-4 w-4" />
                            </Button>
                          )}
                        </div>
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        )}
      </Card>

      {(data?.totalPages ?? 1) > 1 && (
        <div className="flex items-center justify-center gap-2">
          <Button
            variant="outline"
            size="sm"
            disabled={page <= 1}
            onClick={() => setPage((current) => current - 1)}
          >
            Previous
          </Button>
          <span className="text-sm text-muted-foreground">
            Page {page} of {data.totalPages}
          </span>
          <Button
            variant="outline"
            size="sm"
            disabled={page >= data.totalPages}
            onClick={() => setPage((current) => current + 1)}
          >
            Next
          </Button>
        </div>
      )}

      <ConfirmDialog
        open={!!deleteTarget}
        onClose={() => setDeleteTarget(null)}
        onConfirm={handleDelete}
        loading={deleteHistory.isPending}
        title="Delete saved statement?"
        description="The saved PDF and history record will be permanently removed. Its invoices will not be changed."
      />
    </div>
  );
}
